apiVersion: apps/v1
kind: Deployment
metadata:
  name: tomcat-deployment
  labels:
    app: tomcat
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tomcat
  template:
    metadata:
      labels:
        app: tomcat
    spec:
      containers:
      - name: tomcat
        image: tomcat
        ports:
        - containerPort: 8080
        volumeMounts:
        - mountPath: /usr/local/tomcat/webapps/
          name: my-volume
      volumes:
      - name: my-volume
        persistentVolumeClaim:
            claimName: tomcat-volume-claim
---
apiVersion: v1
kind: Service
metadata:
  name: tomcat
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
    nodePort: 30800
  type: NodePort  
  selector:
    app: tomcat
status:
  loadBalancer: {}   
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tomcat-volume-claim
spec:
  storageClassName: slow
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: tomcat-volume
  labels:
    type: local
spec:
  storageClassName: slow
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/Users/ashumilov/projects/dhl/war-dist/target"       